# Importting required package

In [135]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from sklearn.preprocessing import LabelEncoder

warnings.filterwarnings('ignore')

In [136]:
df = sns.load_dataset("iris")

In [137]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [138]:
df['species'].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [139]:
from sklearn.model_selection import train_test_split

In [140]:
X = df.drop('species', axis=1)
y = df['species']

le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [141]:
X_train, X_test, y_train, y_test = train_test_split( X, y_encoded, test_size=0.33, random_state=42)

In [142]:
from sklearn.neighbors import KNeighborsClassifier

In [143]:
knn_model = KNeighborsClassifier(n_neighbors=13)
knn_model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [144]:
knn_y_pred = knn_model.predict(X_test)
knn_y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [145]:
from sklearn.metrics import accuracy_score

In [146]:
accuracy_score(y_test,knn_y_pred)

1.0

In [147]:
from sklearn.svm import SVC

In [148]:
svm_model = SVC( gamma='auto')
svm_model.fit(X_train,y_train)

SVC(gamma='auto')

In [149]:
svm_y_pred = svm_model.predict(X_test)
svm_y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [150]:
accuracy_score(y_test,svm_y_pred)

1.0

In [151]:
from sklearn.model_selection import GridSearchCV

In [152]:
Classifier = GridSearchCV(
    svm_model,
    param_grid= {
        'C': [1,10,20,30], 
        'kernel': ['rbf', 'linear'],
    },
)

In [153]:
Classifier.fit(X_train,y_train)

GridSearchCV(estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [154]:
result = pd.DataFrame(Classifier.cv_results_)

In [155]:
result[['param_C','param_kernel','mean_test_score']].sort_values(by='mean_test_score',ascending=False)

   param_C param_kernel  mean_test_score
1        1       linear             0.95
0        1          rbf             0.94
7       30       linear             0.94
2       10          rbf             0.93
6       30          rbf             0.93
3       10       linear             0.93
5       20       linear             0.93
4       20          rbf             0.92

In [156]:
from sklearn.model_selection import RandomizedSearchCV

In [157]:
Classifier_r = RandomizedSearchCV(
    (svm_model),
    {
        'C': [1,10,20,30], 
        'kernel': ['rbf', 'linear'],
    },
    n_iter = 2
)

In [158]:
Classifier_r.fit(X_train,y_train)

RandomizedSearchCV(estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [159]:
result = pd.DataFrame(Classifier_r.cv_results_)
result[['param_C','param_kernel','mean_test_score']].sort_values(by='mean_test_score',ascending=False)

   param_C param_kernel  mean_test_score
0       20       linear             0.93
1       20          rbf             0.92

# ENSEMBLE LEARNING

In [160]:
from sklearn.ensemble import RandomForestClassifier

In [161]:
rf_model = RandomForestClassifier(
    n_estimators = 100,
    max_depth= None, 
    random_state = 42
)

rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [162]:
rf_y_pred = rf_model.predict(X_test)
rf_y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [163]:
accuracy_score(y_test,rf_y_pred)

0.98

# Boosting

In [164]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier

In [165]:
ab_model = AdaBoostClassifier(
    n_estimators = 100,
    random_state = 42
)

ab_model.fit(X_train,y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [166]:
ad_y_pred = ab_model.predict(X_test)
ad_y_pred

array([1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [167]:
accuracy_score(y_test, ad_y_pred)

0.94

In [168]:
gb_model = GradientBoostingClassifier(
    n_estimators = 100,
    learning_rate=0.1,
    random_state = 42
)

gb_model.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

In [169]:
gd_y_pred = gb_model.predict(X_test)
gd_y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [170]:
accuracy_score(y_test, gd_y_pred)

0.98

In [171]:
xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3,use_label_encoder=False, eval_metric='mlogloss', random_state=42)

xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [172]:
xgb_y_pred = xgb_model.predict(X_test)
xgb_y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [173]:
accuracy_score(y_test, xgb_y_pred)

0.98