In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [3]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [4]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [5]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [7]:
X_min = X.min()
X_max = X.max()
X_scaled = (X-X_min) / (X_max-X_min + 1e-8)

In [8]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [10]:
X_train, X_test, y_train, y_test = train_test_split( X_scaled, y, test_size=0.25, random_state=42)

In [13]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(units=8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [14]:
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics= ['accuracy'])

In [19]:
history = model.fit(
    X_train.values,
    y_train.values,
    validation_data = [X_test.values,y_test.values],
    epochs = 100,
    batch_size = len(X_train),
    verbose = 1
)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.4332 - val_accuracy: 0.7500 - val_loss: 0.5317
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4330 - val_accuracy: 0.7500 - val_loss: 0.5313
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4328 - val_accuracy: 0.7500 - val_loss: 0.5312
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4326 - val_accuracy: 0.7500 - val_loss: 0.5308
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4323 - val_accuracy: 0.7500 - val_loss: 0.5306
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4321 - val_accuracy: 0.7500 - val_loss: 0.5303
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4319 - val_accuracy: 0.7500 - val_loss: 0.5301
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.4317 - val_accuracy: 0.7500 - val_loss: 0.5298
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4315 - val_accuracy: 0.7500 - val_loss: 0.5296
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.4312 - val_accuracy: 0.7500 - val_loss: 0.5294
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4310 - val_accuracy: 0.7500 - val_loss: 0.5290
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.4308 - val_accuracy: 0.7500 - val_loss: 0.5289
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4306 - val_accuracy: 0.7500 - val_loss: 0.5285
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4304 - val_accuracy: 0.7500 - val_loss: 0.5283
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4301 - val_accuracy: 0.7500 - val_loss: 0.5282
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4299 - val_accuracy: 0.7500 - val_loss: 0.5279
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4297 - val_accuracy: 0.7500 - val_loss: 0.5277
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4295 - val_accuracy: 0.7500 - val_loss: 0.5274
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4293 - val_accuracy: 0.7500 - val_loss: 0.5272
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4290 - val_accuracy: 0.7500 - val_loss: 0.5270
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4288 - val_accuracy: 0.7500 - val_loss: 0.5267
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4286 - val_accuracy: 0.7500 - val_loss: 0.5266
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4284 - val_accuracy: 0.7500 - val_loss: 0.5262
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4282 - val_accuracy: 0.7500 - val_loss: 0.5261
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.4280 - val_accuracy: 0.7500 - val_loss: 0.5257
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4278 - val_accuracy: 0.7500 - val_loss: 0.5256
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4275 - val_accuracy: 0.7500 - val_loss: 0.5254
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4273 - val_accuracy: 0.7500 - val_loss: 0.5251
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4271 - val_accuracy: 0.7500 - val_loss: 0.5249
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.4269 - val_accuracy: 0.7500 - val_loss: 0.5246
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4267 - val_accuracy: 0.7500 - val_loss: 0.5244
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4265 - val_accuracy: 0.7500 - val_loss: 0.5243
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4262 - val_accuracy: 0.7500 - val_loss: 0.5240
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4260 - val_accuracy: 0.7500 - val_loss: 0.5238
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.4258 - val_accuracy: 0.7500 - val_loss: 0.5235
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4256 - val_accuracy: 0.7500 - val_loss: 0.5233
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4254 - val_accuracy: 0.7500 - val_loss: 0.5231
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.4252 - val_accuracy: 0.7500 - val_loss: 0.5228
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.4250 - val_accuracy: 0.7500 - val_loss: 0.5227
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.4247 - val_accuracy: 0.7500 - val_loss: 0.5223
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4245 - val_accuracy: 0.7500 - val_loss: 0.5222
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4243 - val_accuracy: 0.7500 - val_loss: 0.5220
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4241 - val_accuracy: 0.7500 - val_loss: 0.5217
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4239 - val_accuracy: 0.7500 - val_loss: 0.5215
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4237 - val_accuracy: 0.7500 - val_loss: 0.5212
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4235 - val_accuracy: 0.7500 - val_loss: 0.5210
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4232 - val_accuracy: 0.7500 - val_loss: 0.5209
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4230 - val_accuracy: 0.7500 - val_loss: 0.5205
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4228 - val_accuracy: 0.7500 - val_loss: 0.5204
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4226 - val_accuracy: 0.7500 - val_loss: 0.5200
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4224 - val_accuracy: 0.7500 - val_loss: 0.5199
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4222 - val_accuracy: 0.7500 - val_loss: 0.5196
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4220 - val_accuracy: 0.7500 - val_loss: 0.5194
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4218 - val_accuracy: 0.7500 - val_loss: 0.5192
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4215 - val_accuracy: 0.7500 - val_loss: 0.5189
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4213 - val_accuracy: 0.7500 - val_loss: 0.5187
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4211 - val_accuracy: 0.7500 - val_loss: 0.5184
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4209 - val_accuracy: 0.7500 - val_loss: 0.5183
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4207 - val_accuracy: 0.7500 - val_loss: 0.5181
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.4205 - val_accuracy: 0.7500 - val_loss: 0.5178
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.4203 - val_accuracy: 0.7500 - val_loss: 0.5176
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.4201 - val_accuracy: 0.7500 - val_loss: 0.5173
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4199 - val_accuracy: 0.7500 - val_loss: 0.5171
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.4196 - val_accuracy: 0.7500 - val_loss: 0.5170
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4194 - val_accuracy: 0.7500 - val_loss: 0.5166
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4192 - val_accuracy: 0.7500 - val_loss: 0.5165
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4190 - val_accuracy: 0.7500 - val_loss: 0.5161
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4188 - val_accuracy: 0.7500 - val_loss: 0.5160
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4186 - val_accuracy: 0.7500 - val_loss: 0.5158
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4184 - val_accuracy: 0.7500 - val_loss: 0.5155
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4182 - val_accuracy: 0.7500 - val_loss: 0.5153
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4179 - val_accuracy: 0.7500 - val_loss: 0.5150
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4177 - val_accuracy: 0.7500 - val_loss: 0.5148
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4175 - val_accuracy: 0.7500 - val_loss: 0.5147
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4173 - val_accuracy: 0.7500 - val_loss: 0.5144
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4171 - val_accuracy: 0.7500 - val_loss: 0.5142
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 1.0000 - loss: 0.4169 - val_accuracy: 0.7500 - val_loss: 0.5139
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4167 - val_accuracy: 0.7500 - val_loss: 0.5137
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4165 - val_accuracy: 0.7500 - val_loss: 0.5135
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4163 - val_accuracy: 0.7500 - val_loss: 0.5132
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4161 - val_accuracy: 0.7500 - val_loss: 0.5131
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.4159 - val_accuracy: 0.7500 - val_loss: 0.5127
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.4156 - val_accuracy: 0.7500 - val_loss: 0.5126
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4154 - val_accuracy: 0.7500 - val_loss: 0.5124
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4152 - val_accuracy: 0.7500 - val_loss: 0.5121
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4150 - val_accuracy: 0.7500 - val_loss: 0.5119
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.4148 - val_accuracy: 0.7500 - val_loss: 0.5116
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4146 - val_accuracy: 0.7500 - val_loss: 0.5114
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4144 - val_accuracy: 0.7500 - val_loss: 0.5113
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4142 - val_accuracy: 0.7500 - val_loss: 0.5110
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4140 - val_accuracy: 0.7500 - val_loss: 0.5108
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4138 - val_accuracy: 0.7500 - val_loss: 0.5105
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.4136 - val_accuracy: 0.7500 - val_loss: 0.5103
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4134 - val_accuracy: 0.7500 - val_loss: 0.5102
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.4131 - val_accuracy: 0.7500 - val_loss: 0.5098
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4129 - val_accuracy: 0.7500 - val_loss: 0.5097
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4127 - val_accuracy: 0.7500 - val_loss: 0.5093
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.4125 - val_accuracy: 0.7500 - val_loss: 0.5092
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.4123 - val_accuracy: 0.7500 - val_loss: 0.5090
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.4121 - val_accuracy: 0.7500 - val_loss: 0.5087

In [20]:
history = model.fit(
    X_train.values,
    y_train.values,
    validation_data = [X_test.values,y_test.values],
    epochs = 100,
    batch_size = 1,
    verbose = 1
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.4157 - val_accuracy: 0.7500 - val_loss: 0.5078
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.4135 - val_accuracy: 0.7500 - val_loss: 0.5040
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.4111 - val_accuracy: 0.7500 - val_loss: 0.5005
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9167 - loss: 0.4081 - val_accuracy: 0.7500 - val_loss: 0.4963
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.4063 - val_accuracy: 0.7500 - val_loss: 0.4955
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.4040 - val_accuracy: 0.7500 - val_loss: 0.4937
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.4014 - val_accuracy: 0.7500 - val_loss: 0.4934
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3995 - val_accuracy: 0.7500 - val_loss: 0.4879
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3972 - val_accuracy: 0.7500 - val_loss: 0.4849
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3949 - val_accuracy: 0.7500 - val_loss: 0.4817
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3927 - val_accuracy: 0.7500 - val_loss: 0.4809
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3903 - val_accuracy: 0.7500 - val_loss: 0.4765
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3879 - val_accuracy: 0.7500 - val_loss: 0.4774
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3859 - val_accuracy: 0.7500 - val_loss: 0.4742
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.3836 - val_accuracy: 0.7500 - val_loss: 0.4745
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.3820 - val_accuracy: 0.7500 - val_loss: 0.4710
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3796 - val_accuracy: 0.7500 - val_loss: 0.4692
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3774 - val_accuracy: 0.7500 - val_loss: 0.4639
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3756 - val_accuracy: 0.7500 - val_loss: 0.4625
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3733 - val_accuracy: 0.7500 - val_loss: 0.4581
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3716 - val_accuracy: 0.7500 - val_loss: 0.4574
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3691 - val_accuracy: 0.7500 - val_loss: 0.4581
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3676 - val_accuracy: 0.7500 - val_loss: 0.4542
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3652 - val_accuracy: 0.7500 - val_loss: 0.4545
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3633 - val_accuracy: 0.7500 - val_loss: 0.4530
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3613 - val_accuracy: 0.7500 - val_loss: 0.4519
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3591 - val_accuracy: 0.7500 - val_loss: 0.4465
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3572 - val_accuracy: 0.7500 - val_loss: 0.4443
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3554 - val_accuracy: 0.7500 - val_loss: 0.4439
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3537 - val_accuracy: 0.7500 - val_loss: 0.4403
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3518 - val_accuracy: 0.7500 - val_loss: 0.4375
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3496 - val_accuracy: 0.7500 - val_loss: 0.4382
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3482 - val_accuracy: 0.7500 - val_loss: 0.4340
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3463 - val_accuracy: 0.7500 - val_loss: 0.4331
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3446 - val_accuracy: 0.7500 - val_loss: 0.4313
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.3429 - val_accuracy: 0.7500 - val_loss: 0.4282
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3410 - val_accuracy: 0.7500 - val_loss: 0.4265
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3393 - val_accuracy: 0.7500 - val_loss: 0.4229
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.3377 - val_accuracy: 0.7500 - val_loss: 0.4227
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3360 - val_accuracy: 0.7500 - val_loss: 0.4223
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3345 - val_accuracy: 0.7500 - val_loss: 0.4195
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3324 - val_accuracy: 0.7500 - val_loss: 0.4206
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3313 - val_accuracy: 0.7500 - val_loss: 0.4185
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3296 - val_accuracy: 0.7500 - val_loss: 0.4148
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3276 - val_accuracy: 0.7500 - val_loss: 0.4120
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.3261 - val_accuracy: 0.7500 - val_loss: 0.4127
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3248 - val_accuracy: 0.7500 - val_loss: 0.4113
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3228 - val_accuracy: 0.7500 - val_loss: 0.4086
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3217 - val_accuracy: 0.7500 - val_loss: 0.4059
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3202 - val_accuracy: 0.7500 - val_loss: 0.4040
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3186 - val_accuracy: 0.7500 - val_loss: 0.4020
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3171 - val_accuracy: 0.7500 - val_loss: 0.3988
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9167 - loss: 0.3156 - val_accuracy: 0.7500 - val_loss: 0.4004
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3142 - val_accuracy: 0.7500 - val_loss: 0.3994
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3128 - val_accuracy: 0.7500 - val_loss: 0.3973
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3104 - val_accuracy: 0.7500 - val_loss: 0.3997
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3101 - val_accuracy: 0.7500 - val_loss: 0.3961
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3079 - val_accuracy: 0.7500 - val_loss: 0.3910
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3071 - val_accuracy: 0.7500 - val_loss: 0.3887
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3059 - val_accuracy: 0.7500 - val_loss: 0.3892
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3044 - val_accuracy: 0.7500 - val_loss: 0.3885
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3027 - val_accuracy: 0.7500 - val_loss: 0.3899
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.3014 - val_accuracy: 0.7500 - val_loss: 0.3901
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.3004 - val_accuracy: 0.7500 - val_loss: 0.3861
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.2988 - val_accuracy: 0.7500 - val_loss: 0.3818
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2977 - val_accuracy: 0.7500 - val_loss: 0.3815
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2964 - val_accuracy: 0.7500 - val_loss: 0.3802
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2950 - val_accuracy: 0.7500 - val_loss: 0.3791
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2934 - val_accuracy: 0.7500 - val_loss: 0.3748
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2923 - val_accuracy: 0.7500 - val_loss: 0.3755
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2913 - val_accuracy: 0.7500 - val_loss: 0.3758
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2896 - val_accuracy: 0.7500 - val_loss: 0.3715
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2889 - val_accuracy: 0.7500 - val_loss: 0.3716
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2873 - val_accuracy: 0.7500 - val_loss: 0.3705
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2863 - val_accuracy: 0.7500 - val_loss: 0.3681
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2849 - val_accuracy: 0.7500 - val_loss: 0.3696
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2830 - val_accuracy: 0.7500 - val_loss: 0.3720
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2827 - val_accuracy: 0.7500 - val_loss: 0.3705
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.2812 - val_accuracy: 0.7500 - val_loss: 0.3704
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2804 - val_accuracy: 0.7500 - val_loss: 0.3664
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2793 - val_accuracy: 0.7500 - val_loss: 0.3647
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2774 - val_accuracy: 0.7500 - val_loss: 0.3600
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2769 - val_accuracy: 0.7500 - val_loss: 0.3608
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2757 - val_accuracy: 0.7500 - val_loss: 0.3604
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2739 - val_accuracy: 0.7500 - val_loss: 0.3628
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2734 - val_accuracy: 0.7500 - val_loss: 0.3614
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2721 - val_accuracy: 0.7500 - val_loss: 0.3626
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2711 - val_accuracy: 0.7500 - val_loss: 0.3624
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2700 - val_accuracy: 0.7500 - val_loss: 0.3621
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2687 - val_accuracy: 0.7500 - val_loss: 0.3559
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2672 - val_accuracy: 0.7500 - val_loss: 0.3572
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2669 - val_accuracy: 0.7500 - val_loss: 0.3527
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2660 - val_accuracy: 0.7500 - val_loss: 0.3528
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2650 - val_accuracy: 0.7500 - val_loss: 0.3511
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2639 - val_accuracy: 0.7500 - val_loss: 0.3501
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2627 - val_accuracy: 0.7500 - val_loss: 0.3487
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2618 - val_accuracy: 0.7500 - val_loss: 0.3453
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2609 - val_accuracy: 0.7500 - val_loss: 0.3459
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2597 - val_accuracy: 0.7500 - val_loss: 0.3426
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.2587 - val_accuracy: 0.7500 - val_loss: 0.3439

In [21]:
history = model.fit(
    X_train.values,
    y_train.values,
    validation_data = [X_test.values,y_test.values],
    epochs = 100,
    batch_size = 4,
    verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.2522 - val_accuracy: 0.7500 - val_loss: 0.3435
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2543 - val_accuracy: 0.7500 - val_loss: 0.3436
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.2517 - val_accuracy: 0.7500 - val_loss: 0.3431
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.2514 - val_accuracy: 0.7500 - val_loss: 0.3431
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.2511 - val_accuracy: 0.7500 - val_loss: 0.3426
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2507 - val_accuracy: 0.7500 - val_loss: 0.3422
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2505 - val_accuracy: 0.7500 - val_loss: 0.3419
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2513 - val_accuracy: 0.7500 - val_loss: 0.3415
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2518 - val_accuracy: 0.7500 - val_loss: 0.3410
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2511 - val_accuracy: 0.7500 - val_loss: 0.3411
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2497 - val_accuracy: 0.7500 - val_loss: 0.3411
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2504 - val_accuracy: 0.7500 - val_loss: 0.3405
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2498 - val_accuracy: 0.7500 - val_loss: 0.3404
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2489 - val_accuracy: 0.7500 - val_loss: 0.3400
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2489 - val_accuracy: 0.7500 - val_loss: 0.3396
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2521 - val_accuracy: 0.7500 - val_loss: 0.3395
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2492 - val_accuracy: 0.7500 - val_loss: 0.3393
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2482 - val_accuracy: 0.7500 - val_loss: 0.3388
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.2492 - val_accuracy: 0.7500 - val_loss: 0.3386
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2472 - val_accuracy: 0.7500 - val_loss: 0.3383
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.2477 - val_accuracy: 0.7500 - val_loss: 0.3384
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2483 - val_accuracy: 0.7500 - val_loss: 0.3383
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2468 - val_accuracy: 0.7500 - val_loss: 0.3378
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2464 - val_accuracy: 0.7500 - val_loss: 0.3378
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2474 - val_accuracy: 0.7500 - val_loss: 0.3380
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2462 - val_accuracy: 0.7500 - val_loss: 0.3376
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2471 - val_accuracy: 0.7500 - val_loss: 0.3374
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2454 - val_accuracy: 0.7500 - val_loss: 0.3370
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2454 - val_accuracy: 0.7500 - val_loss: 0.3367
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.2449 - val_accuracy: 0.7500 - val_loss: 0.3363
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2458 - val_accuracy: 0.7500 - val_loss: 0.3357
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2445 - val_accuracy: 0.7500 - val_loss: 0.3358
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2451 - val_accuracy: 0.7500 - val_loss: 0.3354
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2455 - val_accuracy: 0.7500 - val_loss: 0.3349
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2441 - val_accuracy: 0.7500 - val_loss: 0.3349
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2436 - val_accuracy: 0.7500 - val_loss: 0.3350
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2448 - val_accuracy: 0.7500 - val_loss: 0.3349
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2467 - val_accuracy: 0.7500 - val_loss: 0.3347
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2427 - val_accuracy: 0.7500 - val_loss: 0.3344
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2431 - val_accuracy: 0.7500 - val_loss: 0.3339
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2426 - val_accuracy: 0.7500 - val_loss: 0.3340
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2425 - val_accuracy: 0.7500 - val_loss: 0.3336
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2423 - val_accuracy: 0.7500 - val_loss: 0.3336
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.2430 - val_accuracy: 0.7500 - val_loss: 0.3333
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2421 - val_accuracy: 0.7500 - val_loss: 0.3329
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2430 - val_accuracy: 0.7500 - val_loss: 0.3324
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2430 - val_accuracy: 0.7500 - val_loss: 0.3325
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2414 - val_accuracy: 0.7500 - val_loss: 0.3321
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2407 - val_accuracy: 0.7500 - val_loss: 0.3320
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2412 - val_accuracy: 0.7500 - val_loss: 0.3319
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2399 - val_accuracy: 0.7500 - val_loss: 0.3315
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2398 - val_accuracy: 0.7500 - val_loss: 0.3316
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.2416 - val_accuracy: 0.7500 - val_loss: 0.3313
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2399 - val_accuracy: 0.7500 - val_loss: 0.3310
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2403 - val_accuracy: 0.7500 - val_loss: 0.3305
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2394 - val_accuracy: 0.7500 - val_loss: 0.3302
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2393 - val_accuracy: 0.7500 - val_loss: 0.3304
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2399 - val_accuracy: 0.7500 - val_loss: 0.3305
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2399 - val_accuracy: 0.7500 - val_loss: 0.3300
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2379 - val_accuracy: 0.7500 - val_loss: 0.3301
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2379 - val_accuracy: 0.7500 - val_loss: 0.3298
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2378 - val_accuracy: 0.7500 - val_loss: 0.3296
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2406 - val_accuracy: 0.7500 - val_loss: 0.3292
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2373 - val_accuracy: 0.7500 - val_loss: 0.3292
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2385 - val_accuracy: 0.7500 - val_loss: 0.3294
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2381 - val_accuracy: 0.7500 - val_loss: 0.3291
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2373 - val_accuracy: 0.7500 - val_loss: 0.3286
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2383 - val_accuracy: 0.7500 - val_loss: 0.3281
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2376 - val_accuracy: 0.7500 - val_loss: 0.3277
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2362 - val_accuracy: 0.7500 - val_loss: 0.3278
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2362 - val_accuracy: 0.7500 - val_loss: 0.3280
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2367 - val_accuracy: 0.7500 - val_loss: 0.3280
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2352 - val_accuracy: 0.7500 - val_loss: 0.3277
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2355 - val_accuracy: 0.7500 - val_loss: 0.3275
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2356 - val_accuracy: 0.7500 - val_loss: 0.3273
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2354 - val_accuracy: 0.7500 - val_loss: 0.3269
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2348 - val_accuracy: 0.7500 - val_loss: 0.3265
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2372 - val_accuracy: 0.7500 - val_loss: 0.3268
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2357 - val_accuracy: 0.7500 - val_loss: 0.3263
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2340 - val_accuracy: 0.7500 - val_loss: 0.3259
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2336 - val_accuracy: 0.7500 - val_loss: 0.3260
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2336 - val_accuracy: 0.7500 - val_loss: 0.3260
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2343 - val_accuracy: 0.7500 - val_loss: 0.3260
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2331 - val_accuracy: 0.7500 - val_loss: 0.3256
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2330 - val_accuracy: 0.7500 - val_loss: 0.3255
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2327 - val_accuracy: 0.7500 - val_loss: 0.3255
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2337 - val_accuracy: 0.7500 - val_loss: 0.3252
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2320 - val_accuracy: 0.7500 - val_loss: 0.3249
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2341 - val_accuracy: 0.7500 - val_loss: 0.3247
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2313 - val_accuracy: 0.7500 - val_loss: 0.3243
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2321 - val_accuracy: 0.7500 - val_loss: 0.3245
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2309 - val_accuracy: 0.7500 - val_loss: 0.3244
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2311 - val_accuracy: 0.7500 - val_loss: 0.3240
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2310 - val_accuracy: 0.7500 - val_loss: 0.3239
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2311 - val_accuracy: 0.7500 - val_loss: 0.3236
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2319 - val_accuracy: 0.7500 - val_loss: 0.3236
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2309 - val_accuracy: 0.7500 - val_loss: 0.3234
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2308 - val_accuracy: 0.7500 - val_loss: 0.3230
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2315 - val_accuracy: 0.7500 - val_loss: 0.3231
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.2299 - val_accuracy: 0.7500 - val_loss: 0.3228

In [22]:
from tensorflow.keras import optimizers

In [28]:
# sgd with momentum
opt = optimizers.SGD(learning_rate=0.01, momentum=0.9)

In [29]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics= ['accuracy'])

In [30]:
history1 = model.fit(
    X_train.values,
    y_train.values,
    validation_data = [X_test.values,y_test.values],
    epochs = 100,
    batch_size = 4,
    verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.0294 - val_accuracy: 0.7500 - val_loss: 0.2331
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0292 - val_accuracy: 0.7500 - val_loss: 0.2331
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0293 - val_accuracy: 0.7500 - val_loss: 0.2348
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0293 - val_accuracy: 0.7500 - val_loss: 0.2321
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0294 - val_accuracy: 0.7500 - val_loss: 0.2345
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0294 - val_accuracy: 0.7500 - val_loss: 0.2368
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0293 - val_accuracy: 0.7500 - val_loss: 0.2379
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0292 - val_accuracy: 0.7500 - val_loss: 0.2340
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0289 - val_accuracy: 0.7500 - val_loss: 0.2329
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0288 - val_accuracy: 0.7500 - val_loss: 0.2316
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0290 - val_accuracy: 0.7500 - val_loss: 0.2333
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0292 - val_accuracy: 0.7500 - val_loss: 0.2287
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0289 - val_accuracy: 0.7500 - val_loss: 0.2298
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0289 - val_accuracy: 0.7500 - val_loss: 0.2280
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0285 - val_accuracy: 0.7500 - val_loss: 0.2306
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0290 - val_accuracy: 0.7500 - val_loss: 0.2352
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0290 - val_accuracy: 0.7500 - val_loss: 0.2310
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0287 - val_accuracy: 0.7500 - val_loss: 0.2298
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0284 - val_accuracy: 0.7500 - val_loss: 0.2311
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0283 - val_accuracy: 0.7500 - val_loss: 0.2349
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0281 - val_accuracy: 0.7500 - val_loss: 0.2362
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0281 - val_accuracy: 0.7500 - val_loss: 0.2386
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0286 - val_accuracy: 0.7500 - val_loss: 0.2348
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0281 - val_accuracy: 0.7500 - val_loss: 0.2352
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0286 - val_accuracy: 0.7500 - val_loss: 0.2313
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0283 - val_accuracy: 0.7500 - val_loss: 0.2357
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0279 - val_accuracy: 0.7500 - val_loss: 0.2359
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0281 - val_accuracy: 0.7500 - val_loss: 0.2382
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0280 - val_accuracy: 0.7500 - val_loss: 0.2346
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0281 - val_accuracy: 0.7500 - val_loss: 0.2318
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0280 - val_accuracy: 0.7500 - val_loss: 0.2357
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0276 - val_accuracy: 0.7500 - val_loss: 0.2368
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0279 - val_accuracy: 0.7500 - val_loss: 0.2398
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0278 - val_accuracy: 0.7500 - val_loss: 0.2415
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0276 - val_accuracy: 0.7500 - val_loss: 0.2365
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0274 - val_accuracy: 0.7500 - val_loss: 0.2340
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0278 - val_accuracy: 0.7500 - val_loss: 0.2295
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0272 - val_accuracy: 0.7500 - val_loss: 0.2285
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0276 - val_accuracy: 0.7500 - val_loss: 0.2326
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0270 - val_accuracy: 0.7500 - val_loss: 0.2337
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0275 - val_accuracy: 0.7500 - val_loss: 0.2308
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0272 - val_accuracy: 0.7500 - val_loss: 0.2349
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0270 - val_accuracy: 0.7500 - val_loss: 0.2385
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0270 - val_accuracy: 0.7500 - val_loss: 0.2384
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0269 - val_accuracy: 0.7500 - val_loss: 0.2386
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0269 - val_accuracy: 0.7500 - val_loss: 0.2378
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0266 - val_accuracy: 0.7500 - val_loss: 0.2374
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0268 - val_accuracy: 0.7500 - val_loss: 0.2350
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0268 - val_accuracy: 0.7500 - val_loss: 0.2339
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0269 - val_accuracy: 0.7500 - val_loss: 0.2319
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0265 - val_accuracy: 0.7500 - val_loss: 0.2331
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0263 - val_accuracy: 0.7500 - val_loss: 0.2352
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0268 - val_accuracy: 0.7500 - val_loss: 0.2404
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0263 - val_accuracy: 0.7500 - val_loss: 0.2415
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0263 - val_accuracy: 0.7500 - val_loss: 0.2401
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0263 - val_accuracy: 0.7500 - val_loss: 0.2412
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0263 - val_accuracy: 0.7500 - val_loss: 0.2406
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0266 - val_accuracy: 0.7500 - val_loss: 0.2365
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0260 - val_accuracy: 0.7500 - val_loss: 0.2367
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0260 - val_accuracy: 0.7500 - val_loss: 0.2356
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0259 - val_accuracy: 0.7500 - val_loss: 0.2371
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.0260 - val_accuracy: 0.7500 - val_loss: 0.2357
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0258 - val_accuracy: 0.7500 - val_loss: 0.2373
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0258 - val_accuracy: 0.7500 - val_loss: 0.2360
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0259 - val_accuracy: 0.7500 - val_loss: 0.2386
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0262 - val_accuracy: 0.7500 - val_loss: 0.2426
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0260 - val_accuracy: 0.7500 - val_loss: 0.2389
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0258 - val_accuracy: 0.7500 - val_loss: 0.2403
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0256 - val_accuracy: 0.7500 - val_loss: 0.2373
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0254 - val_accuracy: 0.7500 - val_loss: 0.2360
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0255 - val_accuracy: 0.7500 - val_loss: 0.2372
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0255 - val_accuracy: 0.7500 - val_loss: 0.2359
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0255 - val_accuracy: 0.7500 - val_loss: 0.2345
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0255 - val_accuracy: 0.7500 - val_loss: 0.2373
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0253 - val_accuracy: 0.7500 - val_loss: 0.2392
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0253 - val_accuracy: 0.7500 - val_loss: 0.2395
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0254 - val_accuracy: 0.7500 - val_loss: 0.2379
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0253 - val_accuracy: 0.7500 - val_loss: 0.2403
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0254 - val_accuracy: 0.7500 - val_loss: 0.2432
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0250 - val_accuracy: 0.7500 - val_loss: 0.2407
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0257 - val_accuracy: 0.7500 - val_loss: 0.2353
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0252 - val_accuracy: 0.7500 - val_loss: 0.2340
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0252 - val_accuracy: 0.7500 - val_loss: 0.2389
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0248 - val_accuracy: 0.7500 - val_loss: 0.2404
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0252 - val_accuracy: 0.7500 - val_loss: 0.2375
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0248 - val_accuracy: 0.7500 - val_loss: 0.2390
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0250 - val_accuracy: 0.7500 - val_loss: 0.2426
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0246 - val_accuracy: 0.7500 - val_loss: 0.2441
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0247 - val_accuracy: 0.7500 - val_loss: 0.2425
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0246 - val_accuracy: 0.7500 - val_loss: 0.2429
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0245 - val_accuracy: 0.7500 - val_loss: 0.2413
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0244 - val_accuracy: 0.7500 - val_loss: 0.2401
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0245 - val_accuracy: 0.7500 - val_loss: 0.2404
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0243 - val_accuracy: 0.7500 - val_loss: 0.2401
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0242 - val_accuracy: 0.7500 - val_loss: 0.2408
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0246 - val_accuracy: 0.7500 - val_loss: 0.2378
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0247 - val_accuracy: 0.7500 - val_loss: 0.2426
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0242 - val_accuracy: 0.7500 - val_loss: 0.2411
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0240 - val_accuracy: 0.7500 - val_loss: 0.2412
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 1.0000 - loss: 0.0240 - val_accuracy: 0.7500 - val_loss: 0.2403